<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Ptn.DatabaseChecker</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>CheckNexus.DatabaseComparison.Application.Contracts</PackageId>
    <Description>DTOs and application service contracts for the CheckNexus Database Checker module.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" Version="10.3.0" />
    <PackageReference Include="Volo.Abp.Authorization" Version="10.3.0" />
    <PackageReference Include="Volo.Abp.FluentValidation" Version="10.3.0" />
    <ProjectReference Include="..\Ptn.DatabaseChecker.Domain.Shared\Ptn.DatabaseChecker.Domain.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dtos\Search\" />
    <Folder Include="FluentValidation\Comparisons\" />
    <Folder Include="FluentValidation\Lookups\" />
    <Folder Include="Permissions\Definitions\Comparisons\" />
    <Folder Include="Permissions\Definitions\Lookups\" />
    <Folder Include="Permissions\Definitions\Search\" />
    <Folder Include="Services\Lookups\" />
    <Folder Include="Services\Search\" />
  </ItemGroup>

</Project>
