// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ptn.DatabaseChecker.EntityFrameworkCore;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace Ptn.DatabaseChecker.Migrations
{
    [DbContext(typeof(DatabaseCheckerDbContext))]
    partial class DatabaseCheckerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.PostgreSql)
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ptn.DatabaseChecker.Entities.Connections.DatabaseConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("database_name");

                    b.Property<Guid>("EngineId")
                        .HasColumnType("uuid")
                        .HasColumnName("engine_id");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("host");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<string>("TlsModeCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Require")
                        .HasColumnName("tls_mode_code");

                    b.Property<bool>("TrustServerCertificate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("trust_server_certificate");

                    b.Property<string>("VaultSecretPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("vault_secret_path");

                    b.HasKey("Id")
                        .HasName("pk_database_connections");

                    b.HasIndex("EngineId")
                        .HasDatabaseName("ix_database_connections_engine_id");

                    b.HasIndex("CreatorId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_database_connections_creator_id_name")
                        .HasFilter("\"TenantId\" IS NULL");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("CreatorId", "Name"), false);

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_database_connections_tenant_id_name")
                        .HasFilter("\"TenantId\" IS NOT NULL");

                    b.ToTable("database_connections", "connection");
                });

            modelBuilder.Entity("Ptn.DatabaseChecker.Entities.Definitions.ComparisonDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ComparisonTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparison_type_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("SourceConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_connection_id");

                    b.Property<string>("SourceRoleCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Reference")
                        .HasColumnName("source_role_code");

                    b.Property<Guid>("TargetConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_connection_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.HasKey("Id")
                        .HasName("pk_comparison_definitions");

                    b.HasIndex("ComparisonTypeId")
                        .HasDatabaseName("ix_comparison_definitions_comparison_type_id");

                    b.HasIndex("SourceConnectionId")
                        .HasDatabaseName("ix_comparison_definitions_source_connection_id");

                    b.HasIndex("TargetConnectionId")
                        .HasDatabaseName("ix_comparison_definitions_target_connection_id");

                    b.HasIndex("CreatorId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_comparison_definitions_creator_id_name")
                        .HasFilter("\"TenantId\" IS NULL");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("CreatorId", "Name"), false);

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_comparison_definitions_tenant_id_name")
                        .HasFilter("\"TenantId\" IS NOT NULL");

                    b.ToTable("comparison_definitions", "definition");
                });

            modelBuilder.Entity("Ptn.DatabaseChecker.Entities.Lookups.ComparisonConfidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_comparison_confidences");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_comparison_confidences_code");

                    b.ToTable("comparison_confidences", "lookup");
                });

            modelBuilder.Entity("Ptn.DatabaseChecker.Entities.Lookups.ComparisonRunStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_comparison_run_statuses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_comparison_run_statuses_code");

                    b.ToTable("comparison_run_statuses", "lookup");
                });

            modelBuilder.Entity("Ptn.DatabaseChecker.Entities.Lookups.ComparisonType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_comparison_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_comparison_types_code");

                    b.ToTable("comparison_types", "lookup");
                });

            modelBuilder.Entity("Ptn.DatabaseChecker.Entities.Lookups.DatabaseEngine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_database_engines");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_database_engines_code");

                    b.ToTable("database_engines", "lookup");
                });

            modelBuilder.Entity("Ptn.DatabaseChecker.Entities.Lookups.DifferenceKind", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_difference_kinds");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_difference_kinds_code");

                    b.ToTable("difference_kinds", "lookup");
                });

            modelBuilder.Entity("Ptn.DatabaseChecker.Entities.Lookups.ReportFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_report_formats");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_report_formats_code");

                    b.ToTable("report_formats", "lookup");
                });

            modelBuilder.Entity("Ptn.DatabaseChecker.Entities.Lookups.SchemaObjectType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_schema_object_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_schema_object_types_code");

                    b.ToTable("schema_object_types", "lookup");
                });

            modelBuilder.Entity("Ptn.DatabaseChecker.Entities.Lookups.ScopeKind", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_scope_kinds");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_scope_kinds_code");

                    b.ToTable("scope_kinds", "lookup");
                });

            modelBuilder.Entity("Ptn.DatabaseChecker.Entities.Runs.ComparisonRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ComparisonDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparison_definition_id");

                    b.Property<Guid>("ComparisonTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparison_type_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<int>("DataDifferenceCount")
                        .HasColumnType("integer")
                        .HasColumnName("data_difference_count");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error_message");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<int>("MigrationDifferenceCount")
                        .HasColumnType("integer")
                        .HasColumnName("migration_difference_count");

                    b.Property<int>("SchemaDifferenceCount")
                        .HasColumnType("integer")
                        .HasColumnName("schema_difference_count");

                    b.Property<Guid>("SourceConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_connection_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<Guid>("TargetConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_connection_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.HasKey("Id")
                        .HasName("pk_comparison_runs");

                    b.HasIndex("ComparisonDefinitionId")
                        .HasDatabaseName("ix_comparison_runs_comparison_definition_id");

                    b.HasIndex("ComparisonTypeId")
                        .HasDatabaseName("ix_comparison_runs_comparison_type_id");

                    b.HasIndex("CreationTime")
                        .HasDatabaseName("ix_comparison_runs_creation_time");

                    b.HasIndex("SourceConnectionId")
                        .HasDatabaseName("ix_comparison_runs_source_connection_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_comparison_runs_status_id");

                    b.HasIndex("TargetConnectionId")
                        .HasDatabaseName("ix_comparison_runs_target_connection_id");

                    b.ToTable("comparison_runs", "run");
                });

            modelBuilder.Entity("Ptn.DatabaseChecker.Entities.Connections.DatabaseConnection", b =>
                {
                    b.HasOne("Ptn.DatabaseChecker.Entities.Lookups.DatabaseEngine", "Engine")
                        .WithMany()
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_database_connections_database_engines_engine_id");

                    b.Navigation("Engine");
                });

            modelBuilder.Entity("Ptn.DatabaseChecker.Entities.Definitions.ComparisonDefinition", b =>
                {
                    b.HasOne("Ptn.DatabaseChecker.Entities.Lookups.ComparisonType", "ComparisonType")
                        .WithMany()
                        .HasForeignKey("ComparisonTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comparison_definitions_comparison_types_comparison_type_id");

                    b.HasOne("Ptn.DatabaseChecker.Entities.Connections.DatabaseConnection", "SourceConnection")
                        .WithMany()
                        .HasForeignKey("SourceConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comparison_definitions_database_connections_source_connecti");

                    b.HasOne("Ptn.DatabaseChecker.Entities.Connections.DatabaseConnection", "TargetConnection")
                        .WithMany()
                        .HasForeignKey("TargetConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comparison_definitions_database_connections_target_connecti");

                    b.Navigation("ComparisonType");

                    b.Navigation("SourceConnection");

                    b.Navigation("TargetConnection");
                });

            modelBuilder.Entity("Ptn.DatabaseChecker.Entities.Runs.ComparisonRun", b =>
                {
                    b.HasOne("Ptn.DatabaseChecker.Entities.Definitions.ComparisonDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("ComparisonDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comparison_runs_comparison_definitions_comparison_definitio");

                    b.HasOne("Ptn.DatabaseChecker.Entities.Lookups.ComparisonType", "ComparisonType")
                        .WithMany()
                        .HasForeignKey("ComparisonTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comparison_runs_comparison_types_comparison_type_id");

                    b.HasOne("Ptn.DatabaseChecker.Entities.Connections.DatabaseConnection", "SourceConnection")
                        .WithMany()
                        .HasForeignKey("SourceConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comparison_runs_database_connections_source_connection_id");

                    b.HasOne("Ptn.DatabaseChecker.Entities.Lookups.ComparisonRunStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comparison_runs_comparison_run_statuses_status_id");

                    b.HasOne("Ptn.DatabaseChecker.Entities.Connections.DatabaseConnection", "TargetConnection")
                        .WithMany()
                        .HasForeignKey("TargetConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comparison_runs_database_connections_target_connection_id");

                    b.OwnsOne("Ptn.DatabaseChecker.Models.Comparison.Findings.ComparisonFindings", "Findings", b1 =>
                        {
                            b1.Property<Guid>("ComparisonRunId");

                            b1.HasKey("ComparisonRunId");

                            b1.ToTable("comparison_runs", "run");

                            b1
                                .ToJson("findings")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ComparisonRunId")
                                .HasConstraintName("fk_comparison_runs_comparison_runs_id");

                            b1.OwnsMany("Ptn.DatabaseChecker.Models.Comparison.Findings.DataDifferenceModel", "DataDifferences", b2 =>
                                {
                                    b2.Property<Guid>("ComparisonFindingsComparisonRunId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Fingerprint")
                                        .IsRequired();

                                    b2.Property<bool>("HasRowLevelDifference");

                                    b2.Property<string>("KindCode")
                                        .IsRequired();

                                    b2.Property<long?>("RowCountDifference");

                                    b2.Property<string>("SchemaName")
                                        .IsRequired();

                                    b2.Property<string>("SeverityCode")
                                        .IsRequired();

                                    b2.Property<string>("SourceHash");

                                    b2.Property<long?>("SourceRowCount");

                                    b2.Property<string>("TableName")
                                        .IsRequired();

                                    b2.Property<string>("TargetHash");

                                    b2.Property<long?>("TargetRowCount");

                                    b2.HasKey("ComparisonFindingsComparisonRunId", "__synthesizedOrdinal")
                                        .HasName("pk_comparison_runs");

                                    b2.ToTable("comparison_runs", "run");

                                    b2.WithOwner()
                                        .HasForeignKey("ComparisonFindingsComparisonRunId")
                                        .HasConstraintName("fk_comparison_runs_comparison_runs_comparison_findings_compariso");

                                    b2.OwnsMany("Ptn.DatabaseChecker.Models.Comparison.Findings.DataRowDifferenceModel", "RowDifferences", b3 =>
                                        {
                                            b3.Property<Guid>("DataDifferenceModelComparisonFindingsComparisonRunId");

                                            b3.Property<int>("DataDifferenceModel__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<string>("KindCode")
                                                .IsRequired();

                                            b3.Property<string>("PrimaryKeyValue")
                                                .IsRequired();

                                            b3.HasKey("DataDifferenceModelComparisonFindingsComparisonRunId", "DataDifferenceModel__synthesizedOrdinal", "__synthesizedOrdinal");

                                            b3.ToTable("comparison_runs", "run");

                                            b3.WithOwner()
                                                .HasForeignKey("DataDifferenceModelComparisonFindingsComparisonRunId", "DataDifferenceModel__synthesizedOrdinal")
                                                .HasConstraintName("fk_comparison_runs_comparison_runs_data_difference_model_comparis");

                                            b3.OwnsMany("Ptn.DatabaseChecker.Models.Comparison.Findings.DataValueDifferenceModel", "ValueDifferences", b4 =>
                                                {
                                                    b4.Property<Guid>("DataRowDifferenceModelDataDifferenceModelComparisonFindingsComparisonRunId")
                                                        .HasColumnName("DataRowDifferenceModelDataDifferenceModelComparisonFindingsCom~");

                                                    b4.Property<int>("DataRowDifferenceModelDataDifferenceModel__synthesizedOrdinal");

                                                    b4.Property<int>("DataRowDifferenceModel__synthesizedOrdinal");

                                                    b4.Property<int>("__synthesizedOrdinal")
                                                        .ValueGeneratedOnAdd();

                                                    b4.Property<string>("ColumnName")
                                                        .IsRequired();

                                                    b4.Property<string>("SourceValue");

                                                    b4.Property<string>("TargetValue");

                                                    b4.HasKey("DataRowDifferenceModelDataDifferenceModelComparisonFindingsComparisonRunId", "DataRowDifferenceModelDataDifferenceModel__synthesizedOrdinal", "DataRowDifferenceModel__synthesizedOrdinal", "__synthesizedOrdinal");

                                                    b4.ToTable("comparison_runs", "run");

                                                    b4.WithOwner()
                                                        .HasForeignKey("DataRowDifferenceModelDataDifferenceModelComparisonFindingsComparisonRunId", "DataRowDifferenceModelDataDifferenceModel__synthesizedOrdinal", "DataRowDifferenceModel__synthesizedOrdinal")
                                                        .HasConstraintName("fk_comparison_runs_comparison_runs_data_row_difference_model_data_d");
                                                });

                                            b3.Navigation("ValueDifferences");
                                        });

                                    b2.Navigation("RowDifferences");
                                });

                            b1.OwnsMany("Ptn.DatabaseChecker.Models.Comparison.Findings.MigrationDifferenceModel", "MigrationDifferences", b2 =>
                                {
                                    b2.Property<Guid>("ComparisonFindingsComparisonRunId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Fingerprint")
                                        .IsRequired();

                                    b2.Property<string>("KindCode")
                                        .IsRequired();

                                    b2.Property<string>("MigrationId")
                                        .IsRequired();

                                    b2.Property<string>("SeverityCode")
                                        .IsRequired();

                                    b2.Property<string>("SourceProductVersion");

                                    b2.Property<string>("SourceSchemaName");

                                    b2.Property<string>("TargetProductVersion");

                                    b2.Property<string>("TargetSchemaName");

                                    b2.HasKey("ComparisonFindingsComparisonRunId", "__synthesizedOrdinal")
                                        .HasName("pk_comparison_runs");

                                    b2.ToTable("comparison_runs", "run");

                                    b2.WithOwner()
                                        .HasForeignKey("ComparisonFindingsComparisonRunId")
                                        .HasConstraintName("fk_comparison_runs_comparison_runs_comparison_findings_compariso");
                                });

                            b1.OwnsMany("Ptn.DatabaseChecker.Models.Comparison.Findings.SchemaDifferenceModel", "SchemaDifferences", b2 =>
                                {
                                    b2.Property<Guid>("ComparisonFindingsComparisonRunId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("ChangeSummary");

                                    b2.Property<string>("ChildName");

                                    b2.Property<string>("ConfidenceCode")
                                        .IsRequired();

                                    b2.Property<string>("Fingerprint")
                                        .IsRequired();

                                    b2.Property<string>("KindCode")
                                        .IsRequired();

                                    b2.Property<string>("ObjectName")
                                        .IsRequired();

                                    b2.Property<string>("ObjectTypeCode")
                                        .IsRequired();

                                    b2.Property<string>("SchemaName")
                                        .IsRequired();

                                    b2.Property<string>("SeverityCode")
                                        .IsRequired();

                                    b2.Property<string>("SourceDefinition");

                                    b2.Property<string>("TargetDefinition");

                                    b2.HasKey("ComparisonFindingsComparisonRunId", "__synthesizedOrdinal")
                                        .HasName("pk_comparison_runs");

                                    b2.ToTable("comparison_runs", "run");

                                    b2.WithOwner()
                                        .HasForeignKey("ComparisonFindingsComparisonRunId")
                                        .HasConstraintName("fk_comparison_runs_comparison_runs_comparison_findings_compariso");
                                });

                            b1.Navigation("DataDifferences");

                            b1.Navigation("MigrationDifferences");

                            b1.Navigation("SchemaDifferences");
                        });

                    b.OwnsMany("Ptn.DatabaseChecker.Models.Comparison.Reports.ComparisonReportContent", "Reports", b1 =>
                        {
                            b1.Property<Guid>("ComparisonRunId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Content")
                                .IsRequired();

                            b1.Property<string>("FormatCode")
                                .IsRequired();

                            b1.HasKey("ComparisonRunId", "__synthesizedOrdinal")
                                .HasName("pk_comparison_runs");

                            b1.ToTable("comparison_runs", "run");

                            b1
                                .ToJson("reports")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ComparisonRunId")
                                .HasConstraintName("fk_comparison_runs_comparison_runs_comparison_run_id");
                        });

                    b.Navigation("ComparisonType");

                    b.Navigation("Definition");

                    b.Navigation("Findings")
                        .IsRequired();

                    b.Navigation("Reports");

                    b.Navigation("SourceConnection");

                    b.Navigation("Status");

                    b.Navigation("TargetConnection");
                });
#pragma warning restore 612, 618
        }
    }
}
