// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ptn.TestModule.EntityFrameworkCore;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace Ptn.TestModule.Migrations
{
    [DbContext(typeof(TestModuleDbContext))]
    [Migration("20260815140449_ScenarioQuarantine")]
    partial class ScenarioQuarantine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.PostgreSql)
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ptn.TestModule.Entities.Catalog.TestScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentModelRef")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agent_model_ref");

                    b.Property<string>("ApprovalBoundToHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("approval_bound_to_hash");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<int>("AssertionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("assertion_count");

                    b.Property<bool>("AuthoredByAgent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("authored_by_agent");

                    b.Property<string>("CompiledDocument")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("compiled_document");

                    b.Property<string>("CompiledHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("compiled_hash");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DbConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("db_connection_id");

                    b.Property<string>("DbSchemaFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("db_schema_fingerprint");

                    b.Property<string>("DerivabilityCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("derivability_code");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("notes");

                    b.Property<string>("ProfileFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("profile_fingerprint");

                    b.Property<string>("QuarantineReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("quarantine_reason");

                    b.Property<DateTime?>("QuarantineUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quarantine_until");

                    b.Property<string>("RulesFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rules_fingerprint");

                    b.Property<string>("ScenarioKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("scenario_key");

                    b.Property<string>("SourceDocument")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_document");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_hash");

                    b.Property<string>("SpecFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("spec_fingerprint");

                    b.Property<Guid?>("SpecSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("spec_snapshot_id");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("Id")
                        .HasName("pk_test_scenarios");

                    b.HasIndex("QuarantineUntil")
                        .HasDatabaseName("ix_scenarios_quarantine");

                    b.HasIndex("StateId")
                        .HasDatabaseName("ix_scenarios_state");

                    b.HasIndex("ScenarioKey", "SourceHash")
                        .IsUnique()
                        .HasDatabaseName("ux_scenarios_content");

                    b.HasIndex("ScenarioKey", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("ux_scenarios_version");

                    b.ToTable("test_scenarios", "test_catalog");
                });

            modelBuilder.Entity("Ptn.TestModule.Entities.Lookups.TestFailureCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_test_failure_categories");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_test_failure_categories_code");

                    b.ToTable("test_failure_categories", "test_lookup");
                });

            modelBuilder.Entity("Ptn.TestModule.Entities.Lookups.TestOutcomeStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("BreaksBuild")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("breaks_build");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_test_outcome_statuses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_test_outcome_statuses_code");

                    b.ToTable("test_outcome_statuses", "test_lookup");
                });

            modelBuilder.Entity("Ptn.TestModule.Entities.Lookups.TestRunStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_test_run_statuses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_test_run_statuses_code");

                    b.ToTable("test_run_statuses", "test_lookup");
                });

            modelBuilder.Entity("Ptn.TestModule.Entities.Lookups.TestScenarioState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_test_scenario_states");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_test_scenario_states_code");

                    b.ToTable("test_scenario_states", "test_lookup");
                });

            modelBuilder.Entity("Ptn.TestModule.Entities.Lookups.TestTriggerKind", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_test_trigger_kinds");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_test_trigger_kinds_code");

                    b.ToTable("test_trigger_kinds", "test_lookup");
                });

            modelBuilder.Entity("Ptn.TestModule.Entities.Runs.TestResultFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("ComparisonKindCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("comparison_kind_code");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("EvidenceSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("evidence_summary");

                    b.Property<string>("ExpectedValue")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("expected_value");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("location");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<int?>("ObservedAtMs")
                        .HasColumnType("integer")
                        .HasColumnName("observed_at_ms");

                    b.Property<string>("ObservedValue")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observed_value");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("RuleRef")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rule_ref");

                    b.Property<string>("SourceCheckerCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_checker_code");

                    b.Property<string>("TargetDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("target_display_name");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<Guid>("TestRunResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_run_result_id");

                    b.HasKey("Id")
                        .HasName("pk_test_result_findings");

                    b.HasIndex("Fingerprint")
                        .HasDatabaseName("ix_findings_fingerprint");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_findings_loc");

                    b.HasIndex("RuleRef")
                        .HasDatabaseName("ix_findings_rule");

                    b.HasIndex("SourceCheckerCode")
                        .HasDatabaseName("ix_findings_src");

                    b.HasIndex("TestRunResultId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_findings_order");

                    b.ToTable("test_result_findings", "test_run");
                });

            modelBuilder.Entity("Ptn.TestModule.Entities.Runs.TestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DbConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("db_connection_id");

                    b.Property<string>("DbSchemaFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("db_schema_fingerprint");

                    b.Property<string>("EnvironmentKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("environment_key");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("HarBlobName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("har_blob_name");

                    b.Property<string>("HistoryId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("history_id");

                    b.Property<bool>("IsDryRun")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_dry_run");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<Guid>("RunStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_status_id");

                    b.Property<string>("RunnerRef")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("runner_ref");

                    b.Property<Guid?>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.Property<string>("SpecFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("spec_fingerprint");

                    b.Property<Guid?>("SpecSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("spec_snapshot_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<string>("TestKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("test_key");

                    b.Property<string>("TraceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trace_id");

                    b.Property<Guid>("TriggerKindId")
                        .HasColumnType("uuid")
                        .HasColumnName("trigger_kind_id");

                    b.Property<string>("TriggerRef")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("trigger_ref");

                    b.HasKey("Id")
                        .HasName("pk_test_runs");

                    b.HasIndex("HistoryId")
                        .HasDatabaseName("ix_runs_trend");

                    b.HasIndex("ScenarioId")
                        .HasDatabaseName("ix_test_runs_scenario_id");

                    b.HasIndex("TestKey")
                        .HasDatabaseName("ix_runs_test");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("ix_runs_trace");

                    b.HasIndex("TriggerKindId")
                        .HasDatabaseName("ix_test_runs_trigger_kind_id");

                    b.HasIndex("RunStatusId", "StartedAt")
                        .HasDatabaseName("ix_runs_stale");

                    b.ToTable("test_runs", "test_run");
                });

            modelBuilder.Entity("Ptn.TestModule.Entities.Runs.TestRunResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("attempt");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("CtrfBlobName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ctrf_blob_name");

                    b.Property<string>("Detail")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("detail");

                    b.Property<string>("DiagnosisReport")
                        .HasColumnType("jsonb")
                        .HasColumnName("diagnosis_report");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("FailedStepName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("failed_step_name");

                    b.Property<int?>("FailedStepOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("failed_step_ordinal");

                    b.Property<string>("FailedStepPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failed_step_path");

                    b.Property<Guid?>("FailureCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("failure_category_id");

                    b.Property<string>("JUnitBlobName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("junit_blob_name");

                    b.Property<int?>("LastCompletedOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("last_completed_ordinal");

                    b.Property<Guid>("OutcomeStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("outcome_status_id");

                    b.Property<string>("SarifBlobName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("sarif_blob_name");

                    b.Property<string>("TakenBranchPath")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("taken_branch_path");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<Guid>("TestRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_run_id");

                    b.HasKey("Id")
                        .HasName("pk_test_run_results");

                    b.HasIndex("ErrorCode")
                        .HasDatabaseName("ix_results_error");

                    b.HasIndex("FailureCategoryId")
                        .HasDatabaseName("ix_test_run_results_failure_category_id");

                    b.HasIndex("OutcomeStatusId")
                        .HasDatabaseName("ix_test_run_results_outcome_status_id");

                    b.HasIndex("TestRunId", "Attempt")
                        .IsUnique()
                        .HasDatabaseName("ux_results_attempt");

                    b.ToTable("test_run_results", "test_run");
                });

            modelBuilder.Entity("Ptn.TestModule.Entities.Catalog.TestScenario", b =>
                {
                    b.HasOne("Ptn.TestModule.Entities.Lookups.TestScenarioState", null)
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_scenarios_test_scenario_states_state_id");
                });

            modelBuilder.Entity("Ptn.TestModule.Entities.Runs.TestResultFinding", b =>
                {
                    b.HasOne("Ptn.TestModule.Entities.Runs.TestRunResult", null)
                        .WithMany("Findings")
                        .HasForeignKey("TestRunResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_result_findings_test_run_results_test_run_result_id");
                });

            modelBuilder.Entity("Ptn.TestModule.Entities.Runs.TestRun", b =>
                {
                    b.HasOne("Ptn.TestModule.Entities.Lookups.TestRunStatus", null)
                        .WithMany()
                        .HasForeignKey("RunStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_runs_test_run_statuses_run_status_id");

                    b.HasOne("Ptn.TestModule.Entities.Catalog.TestScenario", null)
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_test_runs_test_scenarios_scenario_id");

                    b.HasOne("Ptn.TestModule.Entities.Lookups.TestTriggerKind", null)
                        .WithMany()
                        .HasForeignKey("TriggerKindId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_runs_test_trigger_kinds_trigger_kind_id");
                });

            modelBuilder.Entity("Ptn.TestModule.Entities.Runs.TestRunResult", b =>
                {
                    b.HasOne("Ptn.TestModule.Entities.Lookups.TestFailureCategory", null)
                        .WithMany()
                        .HasForeignKey("FailureCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_test_run_results_test_failure_categories_failure_category_id");

                    b.HasOne("Ptn.TestModule.Entities.Lookups.TestOutcomeStatus", null)
                        .WithMany()
                        .HasForeignKey("OutcomeStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_run_results_test_outcome_statuses_outcome_status_id");

                    b.HasOne("Ptn.TestModule.Entities.Runs.TestRun", null)
                        .WithMany()
                        .HasForeignKey("TestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_run_results_test_runs_test_run_id");
                });

            modelBuilder.Entity("Ptn.TestModule.Entities.Runs.TestRunResult", b =>
                {
                    b.Navigation("Findings");
                });
#pragma warning restore 612, 618
        }
    }
}
