// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ptn.ApiContractChecker.EntityFrameworkCore;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace Ptn.ApiContractChecker.Migrations
{
    [DbContext(typeof(ApiContractCheckerDbContext))]
    partial class ApiContractCheckerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.PostgreSql)
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ptn.ApiContractChecker.Entities.Lookups.CheckRunStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_check_run_statuses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_check_run_statuses_code");

                    b.ToTable("check_run_statuses", "checker");
                });

            modelBuilder.Entity("Ptn.ApiContractChecker.Entities.Lookups.DifferenceDirection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_difference_directions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_difference_directions_code");

                    b.ToTable("difference_directions", "checker");
                });

            modelBuilder.Entity("Ptn.ApiContractChecker.Entities.Lookups.DifferenceKind", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_difference_kinds");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_difference_kinds_code");

                    b.ToTable("difference_kinds", "checker");
                });

            modelBuilder.Entity("Ptn.ApiContractChecker.Entities.Lookups.DifferenceSeverity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_difference_severities");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_difference_severities_code");

                    b.ToTable("difference_severities", "checker");
                });

            modelBuilder.Entity("Ptn.ApiContractChecker.Entities.Lookups.SpecFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_spec_formats");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_spec_formats_code");

                    b.ToTable("spec_formats", "checker");
                });

            modelBuilder.Entity("Ptn.ApiContractChecker.Entities.Runs.ContractCheckRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BaseSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_snapshot_id");

                    b.Property<int>("BreakingCount")
                        .HasColumnType("integer")
                        .HasColumnName("breaking_count");

                    b.Property<Guid>("CheckRunStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("check_run_status_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<int>("DocsOnlyCount")
                        .HasColumnType("integer")
                        .HasColumnName("docs_only_count");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("error_message");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<int>("NonBreakingCount")
                        .HasColumnType("integer")
                        .HasColumnName("non_breaking_count");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("TargetSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_snapshot_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.HasKey("Id")
                        .HasName("pk_contract_check_runs");

                    b.HasIndex("BaseSnapshotId")
                        .HasDatabaseName("ix_contract_check_runs_base_snapshot_id");

                    b.HasIndex("CheckRunStatusId")
                        .HasDatabaseName("ix_contract_check_runs_check_run_status_id");

                    b.HasIndex("TargetSnapshotId")
                        .HasDatabaseName("ix_contract_check_runs_target_snapshot_id");

                    b.HasIndex("TenantId", "CreationTime")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_contract_check_runs_tenant_id_creation_time");

                    b.HasIndex("TenantId", "TargetSnapshotId")
                        .HasDatabaseName("ix_contract_check_runs_tenant_id_target_snapshot_id");

                    b.ToTable("contract_check_runs", "checker");
                });

            modelBuilder.Entity("Ptn.ApiContractChecker.Entities.Snapshots.SpecContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ByteSize")
                        .HasColumnType("integer")
                        .HasColumnName("byte_size");

                    b.Property<string>("CanonicalHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("canonical_hash");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("media_type");

                    b.Property<string>("RawHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("raw_hash");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.HasKey("Id")
                        .HasName("pk_spec_contents");

                    b.HasIndex("TenantId", "CanonicalHash")
                        .HasDatabaseName("ix_spec_contents_tenant_id_canonical_hash");

                    b.HasIndex("TenantId", "RawHash")
                        .IsUnique()
                        .HasDatabaseName("ix_spec_contents_tenant_id_raw_hash");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TenantId", "RawHash"), false);

                    b.ToTable("spec_contents", "checker");
                });

            modelBuilder.Entity("Ptn.ApiContractChecker.Entities.Snapshots.SpecSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("api_version");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("SpecContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("spec_content_id");

                    b.Property<Guid>("SpecDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("spec_document_id");

                    b.Property<Guid>("SpecFormatId")
                        .HasColumnType("uuid")
                        .HasColumnName("spec_format_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.HasKey("Id")
                        .HasName("pk_spec_snapshots");

                    b.HasIndex("SpecContentId")
                        .HasDatabaseName("ix_spec_snapshots_spec_content_id");

                    b.HasIndex("SpecDocumentId")
                        .HasDatabaseName("ix_spec_snapshots_spec_document_id");

                    b.HasIndex("SpecFormatId")
                        .HasDatabaseName("ix_spec_snapshots_spec_format_id");

                    b.HasIndex("TenantId", "SpecDocumentId", "CreationTime")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_spec_snapshots_tenant_id_spec_document_id_creation_time");

                    b.ToTable("spec_snapshots", "checker");
                });

            modelBuilder.Entity("Ptn.ApiContractChecker.Entities.Sources.SpecDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CheckIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("check_interval_minutes");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsMonitored")
                        .HasColumnType("boolean")
                        .HasColumnName("is_monitored");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked_at");

                    b.Property<string>("LastFetchOutcome")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_fetch_outcome");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<DateTime?>("NextCheckAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_check_at");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("path");

                    b.Property<Guid>("SpecSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("spec_source_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.HasKey("Id")
                        .HasName("pk_spec_documents");

                    b.HasIndex("IsMonitored", "NextCheckAt")
                        .HasDatabaseName("ix_spec_documents_is_monitored_next_check_at");

                    b.HasIndex("SpecSourceId", "DocumentName")
                        .IsUnique()
                        .HasDatabaseName("ix_spec_documents_spec_source_id_document_name");

                    b.ToTable("spec_documents", "checker");
                });

            modelBuilder.Entity("Ptn.ApiContractChecker.Entities.Sources.SpecSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("base_url");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<string>("VaultSecretPath")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("vault_secret_path");

                    b.HasKey("Id")
                        .HasName("pk_spec_sources");

                    b.HasIndex("CreatorId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_spec_sources_creator_id_name")
                        .HasFilter("\"TenantId\" IS NULL");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("CreatorId", "Name"), false);

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_spec_sources_tenant_id_name")
                        .HasFilter("\"TenantId\" IS NOT NULL");

                    b.ToTable("spec_sources", "checker");
                });

            modelBuilder.Entity("Ptn.ApiContractChecker.Entities.Runs.ContractCheckRun", b =>
                {
                    b.HasOne("Ptn.ApiContractChecker.Entities.Snapshots.SpecSnapshot", null)
                        .WithMany()
                        .HasForeignKey("BaseSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contract_check_runs_spec_snapshots_base_snapshot_id");

                    b.HasOne("Ptn.ApiContractChecker.Entities.Lookups.CheckRunStatus", null)
                        .WithMany()
                        .HasForeignKey("CheckRunStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contract_check_runs_check_run_statuses_check_run_status_id");

                    b.HasOne("Ptn.ApiContractChecker.Entities.Snapshots.SpecSnapshot", null)
                        .WithMany()
                        .HasForeignKey("TargetSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contract_check_runs_spec_snapshots_target_snapshot_id");

                    b.OwnsOne("Ptn.ApiContractChecker.Models.Runs.ContractCheckFindings", "Findings", b1 =>
                        {
                            b1.Property<Guid>("ContractCheckRunId");

                            b1.HasKey("ContractCheckRunId");

                            b1.ToTable("contract_check_runs", "checker");

                            b1
                                .ToJson("findings")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ContractCheckRunId")
                                .HasConstraintName("fk_contract_check_runs_contract_check_runs_id");

                            b1.OwnsMany("Ptn.ApiContractChecker.Models.Runs.Finding", "Items", b2 =>
                                {
                                    b2.Property<Guid>("ContractCheckFindingsContractCheckRunId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("DirectionCode")
                                        .IsRequired();

                                    b2.Property<string>("KindCode")
                                        .IsRequired();

                                    b2.Property<string>("NewValue");

                                    b2.Property<string>("OldValue");

                                    b2.Property<string>("SeverityCode")
                                        .IsRequired();

                                    b2.HasKey("ContractCheckFindingsContractCheckRunId", "__synthesizedOrdinal")
                                        .HasName("pk_contract_check_runs");

                                    b2.ToTable("contract_check_runs", "checker");

                                    b2.WithOwner()
                                        .HasForeignKey("ContractCheckFindingsContractCheckRunId")
                                        .HasConstraintName("fk_contract_check_runs_contract_check_runs_contract_check_findin");

                                    b2.OwnsOne("Ptn.ApiContractChecker.Models.Runs.FindingAddress", "Address", b3 =>
                                        {
                                            b3.Property<Guid>("FindingContractCheckFindingsContractCheckRunId");

                                            b3.Property<int>("Finding__synthesizedOrdinal");

                                            b3.Property<string>("HttpMethod");

                                            b3.Property<string>("MediaType");

                                            b3.Property<string>("OperationId");

                                            b3.Property<string>("ParameterName");

                                            b3.Property<string>("Path");

                                            b3.Property<string>("PropertyPath");

                                            b3.Property<string>("ResponseStatus");

                                            b3.Property<string>("SchemaName");

                                            b3.HasKey("FindingContractCheckFindingsContractCheckRunId", "Finding__synthesizedOrdinal")
                                                .HasName("pk_contract_check_runs");

                                            b3.ToTable("contract_check_runs", "checker");

                                            b3.WithOwner()
                                                .HasForeignKey("FindingContractCheckFindingsContractCheckRunId", "Finding__synthesizedOrdinal")
                                                .HasConstraintName("fk_contract_check_runs_contract_check_runs_finding_contract_chec");
                                        });

                                    b2.Navigation("Address")
                                        .IsRequired();
                                });

                            b1.Navigation("Items");
                        });

                    b.Navigation("Findings")
                        .IsRequired();
                });

            modelBuilder.Entity("Ptn.ApiContractChecker.Entities.Snapshots.SpecSnapshot", b =>
                {
                    b.HasOne("Ptn.ApiContractChecker.Entities.Snapshots.SpecContent", "SpecContent")
                        .WithMany()
                        .HasForeignKey("SpecContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_spec_snapshots_spec_contents_spec_content_id");

                    b.HasOne("Ptn.ApiContractChecker.Entities.Sources.SpecDocument", null)
                        .WithMany()
                        .HasForeignKey("SpecDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_spec_snapshots_spec_documents_spec_document_id");

                    b.HasOne("Ptn.ApiContractChecker.Entities.Lookups.SpecFormat", "SpecFormat")
                        .WithMany()
                        .HasForeignKey("SpecFormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_spec_snapshots_spec_formats_spec_format_id");

                    b.Navigation("SpecContent");

                    b.Navigation("SpecFormat");
                });

            modelBuilder.Entity("Ptn.ApiContractChecker.Entities.Sources.SpecDocument", b =>
                {
                    b.HasOne("Ptn.ApiContractChecker.Entities.Sources.SpecSource", null)
                        .WithMany("Documents")
                        .HasForeignKey("SpecSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_spec_documents_spec_sources_spec_source_id");
                });

            modelBuilder.Entity("Ptn.ApiContractChecker.Entities.Sources.SpecSource", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
