<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Ptn.DatabaseChecker</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ptn.DatabaseChecker.Application\Ptn.DatabaseChecker.Application.csproj" />
    <ProjectReference Include="..\Ptn.DatabaseChecker.Domain.Tests\Ptn.DatabaseChecker.Domain.Tests.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

</Project>
